# TiKV Configuration.

[raftstore]
# set store capacity, if no set, use disk capacity.
capacity = "6G"
pd-heartbeat-tick-interval = "2s"
pd-store-heartbeat-tick-interval = "5s"
split-region-check-tick-interval = "1s"

[rocksdb]
max-open-files = 10000

[raftdb]
max-open-files = 10000

[storage.block-cache]
capacity = "128MB"

[storage]
reserve-space = "0MB"

[server]
addr = "127.0.0.1:30160"
status-addr = "127.0.0.1:30180"
